Repository RogerSouza1/e-commerce-vinicola, pull requests merged in 2024-09, with the labels that each got.

#26 ✨feat: Login, Permissionamento, Alterar Usuário e Sessão
  .idea/inspectionProfiles/Project_Default.xml
  .idea/modules.xml
  data/vinicoladb.mv.db
  data/vinicoladb.trace.db
  vinicola/pom.xml
  vinicola/src/main/java/com/orange/vinicola/VinicolaApplication.java
  vinicola/src/main/java/com/orange/vinicola/config/AppConfig.java
  vinicola/src/main/java/com/orange/vinicola/config/CustomAuthenticationFailureHandler.java
  vinicola/src/main/java/com/orange/vinicola/config/SecurityConfig.java
  vinicola/src/main/java/com/orange/vinicola/controller/HomeController.java
  vinicola/src/main/java/com/orange/vinicola/controller/UsuarioController.java
  vinicola/src/main/java/com/orange/vinicola/model/Usuario.java
  vinicola/src/main/java/com/orange/vinicola/repository/UsuarioRepository.java
  vinicola/src/main/java/com/orange/vinicola/service/UsuarioService.java
  vinicola/src/main/resources/application.properties
  vinicola/src/main/resources/templates/editar-usuario.html
  vinicola/src/main/resources/templates/fragments/tabela-usuarios.html
  vinicola/src/main/resources/templates/index.html
  vinicola/src/main/resources/templates/lista-usuarios.html
  vinicola/src/main/resources/templates/login.html
  vinicola/src/main/resources/templates/registrar-funcionario.html
  vinicola/src/test/java/com/orange/vinicola/VinicolaApplicationTests.java
  vinicola/target/classes/application.properties
  vinicola/target/classes/com/orange/vinicola/VinicolaApplication.class
Labels: backoffice

#43 feat: frontend das telas de Login e Index
  data/vinicoladb.mv.db
  vinicola/data/vinicoladb.mv.db
  vinicola/src/main/java/com/orange/vinicola/config/SecurityConfig.java
  vinicola/src/main/java/com/orange/vinicola/controller/HomeController.java
  vinicola/src/main/resources/static/css/style.css
  vinicola/src/main/resources/static/images/logo_winery.png
  vinicola/src/main/resources/static/styles.css
  vinicola/src/main/resources/templates/index.html
  vinicola/src/main/resources/templates/lista-usuarios.html
  vinicola/src/main/resources/templates/login.html
Labels: frontoffice

#46 ✨ feat: Front-end do sprint 1
  vinicola/src/main/resources/static/css/style.css
  vinicola/src/main/resources/static/images/seta.png
  vinicola/src/main/resources/templates/editar-usuario.html
  vinicola/src/main/resources/templates/fragments/tabela-usuarios.html
  vinicola/src/main/resources/templates/index.html
  vinicola/src/main/resources/templates/lista-usuarios.html
  vinicola/src/main/resources/templates/login.html
  vinicola/src/main/resources/templates/registrar-funcionario.html
Labels: frontoffice

#52 fix: Permissionamento da tela de Editar Produto
  data/vinicoladb.mv.db
  vinicola/src/main/java/com/orange/vinicola/controller/ProdutoController.java
  vinicola/src/main/resources/static/css/style.css
  vinicola/src/main/resources/templates/editar-produto.html
  vinicola/src/main/resources/templates/registrar-produto.html
Labels: enhancement, backoffice
